/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RenderWorkbookFileResult {
  kind: string
  path: string
  bytes: number
}
export declare function renderWorkbookToBuffer(payloadJson: string): Promise<unknown>
export declare function renderWorkbookToFile(payloadJson: string): Promise<unknown>
